name: Build Python Script with PyInstaller

on:
  push:
    paths:
      - 'test.py'  # 只在 test.py 被修改时触发
  pull_request:
    paths:
      - 'test.py'  # 在提交 PR 时也触发，确保测试最新的改动

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装 pyinstaller

    - name: Run PyInstaller to compile test.py
      run: |
        pyinstaller --onefile test.py  # 使用 pyinstaller 编译 test.py 脚本

    - name: Upload built executable (optional)
      uses: actions/upload-artifact@v4  # 更新为 v3 版本
      with:
        name: test-executable
        path: dist/test  # 将编译后的可执行文件上传
    - name: Commit and push compiled file to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 token
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dist/test.exe  # 将编译文件添加到 git 索引
        git commit -m "Add compiled executable"  # 提交更改
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}  # 使用 token 进行身份验证并推送
