name: Build Python Script with PyInstaller

on:
  push:
    paths:
      - 'test.py'  # 只在 test.py 被修改时触发
  pull_request:
    paths:
      - 'test.py'  # 在提交 PR 时也触发，确保测试最新的改动

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装 pyinstaller

    - name: Run PyInstaller to compile test.py
      run: |
        pyinstaller --onefile test.py  # 使用 pyinstaller 编译 test.py 脚本

    - name: Upload built executable (optional)
      uses: actions/upload-artifact@v4  # 更新为 v3 版本
      with:
        name: test-executable
        path: dist/test  # 将编译后的可执行文件上传
